apiVersion: v1
kind: Service
metadata:
  name: k8s-nginx
  namespace: default
spec:
  ports:
  - name: k8s-nginx
    nodePort: 31212
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: NodePort
